id = "tql"
name = "TQL"
description = "Zed extension for the Tenzir Query Language (TQL)."
version = "0.1.0"
schema_version = 1
authors = ["Tenzir <engineering@tenzir.com>"]
repository = "https://github.com/tenzir/zed-tql"

[grammars.tql]
repository = "https://github.com/tenzir/tree-sitter-tql"
commit = "bc8ef7586b053fe24998842fffa0e0d23b61e736"
