id = "tql"
name = "TQL"
description = "Tenzir Query Language support."
version = "0.0.1"
schema_version = 1
authors = ["Tenzir <engineering@tenzir.com>"]
repository = "https://github.com/tenzir/zed-tql"

[grammars.tql]
repository = "https://github.com/tenzir/tree-sitter-tql"
commit = "2b20201d17048af59f71a6350335a6ea1b166dc5"
