id = "tql"
name = "TQL"
description = "Zed extension for the Tenzir Query Language (TQL)."
version = "0.1.0"
schema_version = 1
authors = ["Tenzir <engineering@tenzir.com>"]
repository = "https://github.com/tenzir/zed-tql"

[grammars.tql]
repository = "https://github.com/tenzir/tree-sitter-tql"
commit = "cefc69ce657f43eaed78db26f1e9e4a260a318dd"
