;; Auto-generated by scripts/sync-zed-extension.mjs. DO NOT EDIT.

[
  "let"
  "if"
  "else"
  "match"
  "and"
  "or"
  "not"
  "move"
  "in"
] @keyword

"this" @variable.builtin

"_" @variable.builtin

"null" @constant.builtin

[
  "true"
  "false"
] @boolean

(dollar_var) @variable.special
(meta_selector) @attribute
(number) @number
(string) @string
(format_expr) @string
(ip) @constant
(subnet) @constant
(time) @number
(duration) @number
(comment) @comment

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

[
  ","
  ";"
] @punctuation.delimiter

[
  "="
  "=>"
  "|"
  "?"
  ":"
  "..."
  "::"
  "=="
  "!="
  ">"
  ">="
  "<"
  "<="
  "+"
  "-"
  "*"
  "/"
] @operator
