;; Auto-generated by tenzir/tree-sitter-tql/scripts/generate-injections.mjs. DO NOT EDIT.

;; Highlight YAML frontmatter using the YAML grammar.

(frontmatter
  body: (frontmatter_body) @injection.content
  (#set! injection.language "yaml")
  (#set! injection.combined)
  (#set! injection.include-children))
